# Generated by Django 3.2.19 on 2023-11-27 02:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=150)),
                ('model', models.CharField(choices=[('li', 'light'), ('me', 'medium'), ('cr', 'cruiser'), ('he', 'heavy')], default=0, max_length=2)),
                ('weightLimit', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)])),
                ('batteryCapacity', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('id', 'IDLE'), ('log', 'LOADING'), ('lod', 'LOADED'), ('deg', 'DELIVERING'), ('ded', 'DELIVERED'), ('ret', 'RETURN')], default=0, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_-]*$', 'Only alphanumeric characters, underscore and middlescore are allowed.')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('code', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[0-9A-Z_]*$', 'Only alphanumeric characters and underscore are allowed.')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('dron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dron')),
            ],
        ),
    ]
