# Generated by Django 3.2.19 on 2023-11-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dron',
            name='model',
            field=models.CharField(choices=[('li', 'light'), ('me', 'medium'), ('cr', 'cruiser'), ('he', 'heavy')], default=0, max_length=7),
        ),
    ]
