# Generated by Django 3.2.19 on 2023-11-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dron_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
