# Generated by Django 3.2.19 on 2023-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_drug_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='dron',
        ),
        migrations.AddField(
            model_name='drug',
            name='dron',
            field=models.ManyToManyField(blank=True, null=True, to='api.Dron'),
        ),
    ]
